name=SimpleUART
version=1.0.0
author= asa-lab-bit
maintainer= asa-lab-bit
sentence=A lightweight, template-based UART library for ATtiny 0-series.
paragraph=This library is optimized for ATtiny402/202 to minimize RAM usage using C++ templates and interrupt-driven RX.
category=Communication
url=https://github.com/asa-lab-bit/SimpleUART
architectures=megaavr